<script>
   /*jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);
   jsPrintSetup.setOption('marginTop', 5);
   jsPrintSetup.setOption('marginBottom', 5);
   jsPrintSetup.setOption('marginLeft', 5);
   jsPrintSetup.setOption('marginRight', 5);*/
   // set page header
   //jsPrintSetup.setOption('headerStrLeft', 'Molino Avila');
   //jsPrintSetup.setOption('headerStrCenter', '');
   //jsPrintSetup.setOption('headerStrRight', '&PT');
   // set empty page footer
   //jsPrintSetup.setOption('footerStrLeft', '');
   //jsPrintSetup.setOption('footerStrCenter', '');
   //jsPrintSetup.setOption('footerStrRight', '');
   // clears user preferences always silent print value
   // to enable using 'printSilent' option
   /*jsPrintSetup.clearSilentPrint();
   // Suppress print dialog (for this context only)
   jsPrintSetup.setOption('printSilent', 1);
   // Do Print
   // When print is submitted it is executed asynchronous and
   // script flow continues after print independently of completetion of print process!
   jsPrintSetup.print();*/
</script>

<style>
  .documento_bordes{
    padding: 5px 5px 5px 5px;
    font-size: 12px;
  }
  .documento_superior{
    height: 100px;

  }
  .documento_espacios_persona {
    padding-top: 5px;
    padding-left: 90px;
  }
  .documento_fecha_espacios{
    padding-left: 300px;
  }
  .documento_row_cantidad{
    width: 120px;
    padding-left: 90px;
    padding-top: 5px;
  }
  .documento_row_descripcion{
    width: 760px;
    padding-left: 9px;
    padding-top: 5px;
  }
  .documento_row_pu{
    width: 130px;
    padding-left: 9px;
    padding-top: 5px;
  }
  .documento_espacios_tabla {
    padding-top: 10px;
    width: 100%;
  }
</style>
</head>

<body class="documento_bordes">
  <!--  <div class="invoice-box">-->
        <div class="documento_superior" >
        </div>
        <table cellpadding="0" cellspacing="0" border="0" style="width:100%;letter-spacing: 3pt;">
            <tr class="top">
                <td colspan="4" class="documento_fecha_espacios">
                    <table border="0" >
                        <tr>
                            <td style="width:50px;">
                              15
                            </td>

                            <td style="width:180px;text-align:right;">
                              Septiembre
                            </td>
                            <td style="width:100px;text-align:right;">
                              7
                            </td>

                        </tr>
                    </table>
                </td>
            </tr>

            <tr >
                <td >
                    <table >

                          <?php
                            foreach ((array)$cliente->data as $row)
                            { ?>
                              <tr>
                                  <td class="documento_espacios_persona">
                                    <?php echo $row->nomcompleto;  ?>
                                  </td>
                              </tr>
                              <tr>
                                  <td class="documento_espacios_persona">
                                   <?php echo $row->domiciper;  ?><br>
                                 </td>
                              </tr>
                              <tr>
                                 <td class="documento_espacios_persona">
                                   <?php echo $row->numrucper;  ?> <br>
                                 </td>

                            </tr>
                          <?php  }

                          ?>


                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="4"></td>
            </tr>
            <tr>

                <table  border="0" class="documento_espacios_tabla" style="width:100%;letter-spacing: 3pt;">
                <tr>
                    <td colspan="4" style="padding-top:10px;"></td>
                </tr>
            <?php
               $totalVenta=0;
               $maxItem = 10;
               $items   = 1;
               foreach ((array) $detalle->data as $row)
               { ?>
                 <tr >
                    <td class="documento_row_cantidad" >
                      <?php echo   number_format($row->cantidad,0,'.',' ');   ?>
                    </td>

                     <td class="documento_row_descripcion">
                         <?php echo $row->descripcion;   ?>
                     </td>
                     <td class="documento_row_pu">
                        <?php echo  number_format($row->precio,2,'.',' ') ;   ?>
                     </td>

                       <td>
                          <?php
                            echo number_format($row->total,2,'.',' ');
                            $totalVenta = $totalVenta + $row->total;
                          ?>

                     </td>
                   </tr>
            <?php
                  $items = $items + 1;
                }

                for($items ; $items<=$maxItem;$items++){
                  ?>
                  <tr >
                     <td colspan="4" style="height:20px;" >
                     </td>

                    </tr>
          <?php
              }
            ?>
                </table>
            </tr>

        </table>
  <!--  </div> -->
